### ISSUE TITLE
Argument mismatch in Emacs 25.2 for `line-number-at-pos`

### ISSUE THREAD

**Issue by deb0ch** [hinrik/total-lines#1]
I don't know if the prototype of this function is any different in older versions of Emacs, but in my 25.2.1 Emacs there is only one possible argument:

```
line-number-at-pos is a compiled Lisp function in ‘simple.el’.

(line-number-at-pos &optional POS)

Return (narrowed) buffer line number at position POS.
If POS is nil, use current buffer location.
Counting starts at (point-min), so the value refers
to the contents of the accessible portion of the buffer.

[back]
```

line 44 in `total-lines-init` the extra `t` argument makes the mode not work.

**Comment by hinrik** [comment]
Yeah, apparently the additional argument was [added a few months ago](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=26417). I'll patch the mode to accomplish the same in a different way.

**Comment by deb0ch** [comment]
Or maybe a condition on the current version of Emacs, to still take advantage of the new API ?

Too bad that this new API it is not backward compatible.
